url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

exclude:
  - "*.sh"
  - README.md

#plugins:
#  - jekyll-datapage-generator

page_gen:
  - data: 'foods'
    template: 'foods'
    name: 'food-name'
    dir: 'foods'
